Implementar rele
PI2-Robo-Pintor/painter-robot-esp32 pull request #3
Opened 2023-06-15 14:52 UTC by gustavoduartemoreira

Senhores, podem dar uma olhada ae se a implementação é assim msm? ainda não defini a porta, não tive com testar essa parada!

2023-06-15 19:14 UTC, yudi-azvd requested changes

2023-06-15 19:14 UTC, yudi-azvd commented on main/rele.cpp
> +    gpio_set_level(m_rele, !level); // Inverte o estado do relé
```suggestion
    gpio_set_level(m_rele, !level); // Inverte o estado do relé
```

Revê esse pedaço. Acho que não tem como ler num pino que foi definido como output

2023-06-15 19:14 UTC, yudi-azvd commented on main/rele.cpp
> +        rele->print(); // Exibe o estado do relé
Tá faltando ler da fila, verificar se tem alguma mensagem nela.

2023-06-15 19:14 UTC, yudi-azvd commented on main/rele.h
> +#define _RELE_H
```suggestion
#pragma once
```

2023-06-15 19:14 UTC, yudi-azvd commented on main/rele.h
> +#endif // _RELE_H
```suggestion
```

Usando `#pragma once` não precisa de header guards

2023-06-15 19:16 UTC, yudi-azvd commented
@gustavoduartemoreira 

Faltou também integrar esse código na main. Por enquanto vc pode usar o pino 2 que é a LED interna.

2023-06-17 20:08 UTC, gustavoduartemoreira commented on main/rele.h
> +#define _RELE_H
O pragma once foi adicionando

2023-06-20 21:05 UTC, yudi-azvd approved these changes

2023-06-21 18:01 UTC, merged